# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
    ports:
      - 8000:80
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./cabecalho.php:/var/www/html/cabecalho.php
      - ./navbar.php:/var/www/html/navbar.php
      - ./sobre-mim.php:/var/www/html/sobre-mim.php
      - ./noticias.php:/var/www/html/noticias.php
      - ./footer.php:/var/www/html/footer.php
      - ./jogos/index.php:/var/www/html/jogos/index.php
      - ./jogos/linhaamarela/index.php:/var/www/html/jogos/linhaamarela/index.php
      - ./jogos/linhaamarela/game.php:/var/www/html/jogos/linhaamarela/game.php
      - ./jogos/linhaamarela/fast-game.php:/var/www/html/jogos/linhaamarela/fast-game.php
      - ./jogos/combo-memo/:/var/www/html/jogos/combo-memo/
      - ./jogos/caca-palavras/:/var/www/html/jogos/caca-palavras/
      - ./jogos/palavras-cruzadas/:/var/www/html/jogos/palavras-cruzadas/
      - ./loja_virtual/:/var/www/html/loja_virtual/
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SMTP_HOST: ${DB_PASS}
      SMTP_AUTH: ${SMTP_AUTH}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_PORT: ${SMTP_PORT}

# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker-compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

